INSERT INTO countries (name, iso_code_alpha_3, iso_code_alpha_2, numeric_code, is_active, created_at, updated_at)
VALUES
('Abkhazia', 'ABH', 'GE', 281, 1, NOW(), NOW()),
('Afghanistan', 'AFG', 'AF', 4, 1, NOW(), NOW()),
('Albania', 'ALB', 'AL', 8, 1, NOW(), NOW()),
('Algeria', 'DZA', 'DZ', 12, 1, NOW(), NOW()),
('Andorra', 'AND', 'AD', 20, 1, NOW(), NOW()),
('Angola', 'AGO', 'AO', 24, 1, NOW(), NOW()),
('Antigua and Barbuda', 'ATG', 'AG', 28, 1, NOW(), NOW()),
('Argentina', 'ARG', 'AR', 32, 1, NOW(), NOW()),
('Armenia', 'ARM', 'AM', 51, 1, NOW(), NOW()),
('Australia', 'AUS', 'AU', 36, 1, NOW(), NOW()),
('Austria', 'AUT', 'AT', 40, 1, NOW(), NOW()),
('Azerbaijan', 'AZE', 'AZ', 31, 1, NOW(), NOW()),
('Bahamas', 'BHS', 'BS', 44, 1, NOW(), NOW()),
('Bahrain', 'BHR', 'BH', 48, 1, NOW(), NOW()),
('Bangladesh', 'BGD', 'BD', 50, 1, NOW(), NOW()),
('Barbados', 'BRB', 'BB', 52, 1, NOW(), NOW()),
('Belarus', 'BLR', 'BY', 112, 1, NOW(), NOW()),
('Belgium', 'BEL', 'BE', 56, 1, NOW(), NOW()),
('Belize', 'BLZ', 'BZ', 84, 1, NOW(), NOW()),
('Benin', 'BEN', 'BJ', 204, 1, NOW(), NOW()),
('Bhutan', 'BTN', 'BT', 64, 1, NOW(), NOW()),
('Bolivia', 'BOL', 'BO', 68, 1, NOW(), NOW()),
('Bosnia and Herzegovina', 'BIH', 'BA', 70, 1, NOW(), NOW()),
('Botswana', 'BWA', 'BW', 72, 1, NOW(), NOW()),
('Brazil', 'BRA', 'BR', 76, 1, NOW(), NOW()),
('Brunei Darussalam', 'BRN', 'BN', 96, 1, NOW(), NOW()),
('Bulgaria', 'BGR', 'BG', 100, 1, NOW(), NOW()),
('Burkina Faso', 'BFA', 'BF', 854, 1, NOW(), NOW()),
('Burundi', 'BDI', 'BI', 108, 1, NOW(), NOW()),
('Cabo Verde', 'CPV', 'CV', 132, 1, NOW(), NOW()),
('Cambodia', 'KHM', 'KH', 116, 1, NOW(), NOW()),
('Cameroon', 'CMR', 'CM', 120, 1, NOW(), NOW()),
('Canada', 'CAN', 'CA', 124, 1, NOW(), NOW()),
('Central African Republic', 'CAF', 'CF', 140, 1, NOW(), NOW()),
('Chad', 'TCD', 'TD', 148, 1, NOW(), NOW()),
('Chile', 'CHL', 'CL', 152, 1, NOW(), NOW()),
('China', 'CHN', 'CN', 156, 1, NOW(), NOW()),
('Colombia', 'COL', 'CO', 170, 1, NOW(), NOW()),
('Comoros', 'COM', 'KM', 174, 1, NOW(), NOW()),
('Congo (Congo-Brazzaville)', 'COG', 'CG', 178, 1, NOW(), NOW()),
('Congo (DRC)', 'COD', 'CD', 180, 1, NOW(), NOW()),
('Costa Rica', 'CRI', 'CR', 188, 1, NOW(), NOW()),
('Croatia', 'HRV', 'HR', 191, 1, NOW(), NOW()),
('Cuba', 'CUB', 'CU', 192, 1, NOW(), NOW()),
('Cyprus', 'CYP', 'CY', 196, 1, NOW(), NOW()),
('Czech Republic', 'CZE', 'CZ', 203, 1, NOW(), NOW()),
('Denmark', 'DNK', 'DK', 208, 1, NOW(), NOW()),
('Djibouti', 'DJI', 'DJ', 262, 1, NOW(), NOW()),
('Dominica', 'DMA', 'DM', 212, 1, NOW(), NOW()),
('Dominican Republic', 'DOM', 'DO', 214, 1, NOW(), NOW()),
('Ecuador', 'ECU', 'EC', 218, 1, NOW(), NOW()),
('Egypt', 'EGY', 'EG', 818, 1, NOW(), NOW()),
('El Salvador', 'SLV', 'SV', 222, 1, NOW(), NOW()),
('Equatorial Guinea', 'GNQ', 'GQ', 226, 1, NOW(), NOW()),
('Eritrea', 'ERI', 'ER', 232, 1, NOW(), NOW()),
('Estonia', 'EST', 'EE', 233, 1, NOW(), NOW()),
('Eswatini', 'SWZ', 'SZ', 748, 1, NOW(), NOW()),
('Ethiopia', 'ETH', 'ET', 231, 1, NOW(), NOW()),
('Fiji', 'FJI', 'FJ', 242, 1, NOW(), NOW()),
('Finland', 'FIN', 'FI', 246, 1, NOW(), NOW()),
('France', 'FRA', 'FR', 250, 1, NOW(), NOW()),
('Gabon', 'GAB', 'GA', 266, 1, NOW(), NOW()),
('Gambia', 'GMB', 'GM', 270, 1, NOW(), NOW()),
('Georgia', 'GEO', 'GE', 268, 1, NOW(), NOW()),
('Germany', 'DEU', 'DE', 276, 1, NOW(), NOW()),
('Ghana', 'GHA', 'GH', 288, 1, NOW(), NOW()),
('Greece', 'GRC', 'GR', 300, 1, NOW(), NOW()),
('Grenada', 'GRD', 'GD', 308, 1, NOW(), NOW()),
('Guatemala', 'GTM', 'GT', 320, 1, NOW(), NOW()),
('Guinea', 'GIN', 'GN', 324, 1, NOW(), NOW()),
('Guinea-Bissau', 'GNB', 'GW', 624, 1, NOW(), NOW()),
('Guyana', 'GUY', 'GY', 328, 1, NOW(), NOW()),
('Haiti', 'HTI', 'HT', 332, 1, NOW(), NOW()),
('Honduras', 'HND', 'HN', 340, 1, NOW(), NOW()),
('Hungary', 'HUN', 'HU', 348, 1, NOW(), NOW()),
('Iceland', 'ISL', 'IS', 352, 1, NOW(), NOW()),
('India', 'IND', 'IN', 356, 1, NOW(), NOW()),
('Indonesia', 'IDN', 'ID', 360, 1, NOW(), NOW()),
('Iran', 'IRN', 'IR', 364, 1, NOW(), NOW()),
('Iraq', 'IRQ', 'IQ', 368, 1, NOW(), NOW()),
('Ireland', 'IRL', 'IE', 372, 1, NOW(), NOW()),
('Israel', 'ISR', 'IL', 376, 1, NOW(), NOW()),
('Italy', 'ITA', 'IT', 380, 1, NOW(), NOW()),
('Jamaica', 'JAM', 'JM', 388, 1, NOW(), NOW()),
('Japan', 'JPN', 'JP', 392, 1, NOW(), NOW()),
('Jordan', 'JOR', 'JO', 400, 1, NOW(), NOW()),
('Kazakhstan', 'KAZ', 'KZ', 398, 1, NOW(), NOW()),
('Kenya', 'KEN', 'KE', 404, 1, NOW(), NOW()),
('Kiribati', 'KIR', 'KI', 296, 1, NOW(), NOW()),
('Korea (North)', 'PRK', 'KP', 408, 1, NOW(), NOW()),
('Kuwait', 'KWT', 'KW', 414, 1, NOW(), NOW()),
('Kyrgyzstan', 'KGZ', 'KG', 417, 1, NOW(), NOW()),
('Laos', 'LAO', 'LA', 418, 1, NOW(), NOW()),
('Latvia', 'LVA', 'LV', 428, 1, NOW(), NOW()),
('Lebanon', 'LBN', 'LB', 422, 1, NOW(), NOW()),
('Lesotho', 'LSO', 'LS', 426, 1, NOW(), NOW()),
('Liberia', 'LBR', 'LR', 430, 1, NOW(), NOW()),
('Libya', 'LBY', 'LY', 434, 1, NOW(), NOW()),
('Liechtenstein', 'LIE', 'LI', 438, 1, NOW(), NOW()),
('Lithuania', 'LTU', 'LT', 440, 1, NOW(), NOW()),
('Luxembourg', 'LUX', 'LU', 442, 1, NOW(), NOW()),
('Madagascar', 'MDG', 'MG', 450, 1, NOW(), NOW()),
('Malawi', 'MWI', 'MW', 454, 1, NOW(), NOW()),
('Malaysia', 'MYS', 'MY', 458, 1, NOW(), NOW()),
('Maldives', 'MDV', 'MV', 462, 1, NOW(), NOW()),
('Mali', 'MLI', 'ML', 466, 1, NOW(), NOW()),
('Malta', 'MLT', 'MT', 470, 1, NOW(), NOW()),
('Marshall Islands', 'MHL', 'MH', 584, 1, NOW(), NOW()),
('Mauritania', 'MRT', 'MR', 478, 1, NOW(), NOW()),
('Mauritius', 'MUS', 'MU', 480, 1, NOW(), NOW()),
('Mexico', 'MEX', 'MX', 484, 1, NOW(), NOW()),
('Micronesia', 'FSM', 'FM', 583, 1, NOW(), NOW()),
('Moldova', 'MDA', 'MD', 498, 1, NOW(), NOW()),
('Monaco', 'MCO', 'MC', 492, 1, NOW(), NOW()),
('Mongolia', 'MNG', 'MN', 496, 1, NOW(), NOW()),
('Montenegro', 'MNE', 'ME', 499, 1, NOW(), NOW()),
('Morocco', 'MAR', 'MA', 504, 1, NOW(), NOW()),
('Mozambique', 'MOZ', 'MZ', 508, 1, NOW(), NOW()),
('Myanmar', 'MMR', 'MM', 104, 1, NOW(), NOW()),
('Namibia', 'NAM', 'NA', 516, 1, NOW(), NOW()),
('Nauru', 'NRU', 'NR', 520, 1, NOW(), NOW()),
('Nepal', 'NPL', 'NP', 524, 1, NOW(), NOW()),
('Netherlands', 'NLD', 'NL', 528, 1, NOW(), NOW()),
('New Zealand', 'NZL', 'NZ', 554, 1, NOW(), NOW()),
('Nicaragua', 'NIC', 'NI', 558, 1, NOW(), NOW()),
('Niger', 'NER', 'NE', 562, 1, NOW(), NOW()),
('Nigeria', 'NGA', 'NG', 566, 1, NOW(), NOW()),
('North Macedonia', 'MKD', 'MK', 807, 1, NOW(), NOW()),
('Norway', 'NOR', 'NO', 578, 1, NOW(), NOW()),
('Oman', 'OMN', 'OM', 512, 1, NOW(), NOW()),
('Pakistan', 'PAK', 'PK', 586, 1, NOW(), NOW()),
('Palau', 'PLW', 'PW', 585, 1, NOW(), NOW()),
('Palestine', 'PSE', 'PS', '275', true, NOW(), NOW()),
('Panama', 'PAN', 'PA', 591, 1, NOW(), NOW()),
('Papua New Guinea', 'PNG', 'PG', 598, 1, NOW(), NOW()),
('Paraguay', 'PRY', 'PY', 600, 1, NOW(), NOW()),
('Peru', 'PER', 'PE', 604, 1, NOW(), NOW()),
('Philippines', 'PHL', 'PH', 608, 1, NOW(), NOW()),
('Poland', 'POL', 'PL', 616, 1, NOW(), NOW()),
('Portugal', 'PRT', 'PT', 620, 1, NOW(), NOW()),
('Qatar', 'QAT', 'QA', 634, 1, NOW(), NOW()),
('Romania', 'ROU', 'RO', 642, 1, NOW(), NOW()),
('Russia', 'RUS', 'RU', 643, 1, NOW(), NOW()),
('Rwanda', 'RWA', 'RW', 646, 1, NOW(), NOW()),
('Saint Kitts and Nevis', 'KNA', 'KN', 659, 1, NOW(), NOW()),
('Saint Lucia', 'LCA', 'LC', 662, 1, NOW(), NOW()),
('Saint Vincent and the Grenadines', 'VCT', 'VC', 670, 1, NOW(), NOW()),
('Samoa', 'WSM', 'WS', 882, 1, NOW(), NOW()),
('San Marino', 'SMR', 'SM', 674, 1, NOW(), NOW()),
('Sao Tome and Principe', 'STP', 'ST', 678, 1, NOW(), NOW()),
('Saudi Arabia', 'SAU', 'SA', 682, 1, NOW(), NOW()),
('Senegal', 'SEN', 'SN', 686, 1, NOW(), NOW()),
('Serbia', 'SRB', 'RS', 688, 1, NOW(), NOW()),
('Seychelles', 'SYC', 'SC', 690, 1, NOW(), NOW()),
('Sierra Leone', 'SLE', 'SL', 694, 1, NOW(), NOW()),
('Singapore', 'SGP', 'SG', 702, 1, NOW(), NOW()),
('Slovakia', 'SVK', 'SK', 703, 1, NOW(), NOW()),
('Slovenia', 'SVN', 'SI', 705, 1, NOW(), NOW()),
('Solomon Islands', 'SLB', 'SB', 90, 1, NOW(), NOW()),
('Somalia', 'SOM', 'SO', 706, 1, NOW(), NOW()),
('South Africa', 'ZAF', 'ZA', 710, 1, NOW(), NOW()),
('South Korea', 'KOR', 'KR', 410, 1, NOW(), NOW()),
('South Sudan', 'SSD', 'SS', 728, 1, NOW(), NOW()),
('Spain', 'ESP', 'ES', 724, 1, NOW(), NOW()),
('Sri Lanka', 'LKA', 'LK', 144, 1, NOW(), NOW()),
('Sudan', 'SDN', 'SD', 729, 1, NOW(), NOW()),
('Suriname', 'SUR', 'SR', 740, 1, NOW(), NOW()),
('Sweden', 'SWE', 'SE', 752, 1, NOW(), NOW()),
('Switzerland', 'CHE', 'CH', 756, 1, NOW(), NOW()),
('Syria', 'SYR', 'SY', 760, 1, NOW(), NOW()),
('Taiwan', 'TWN', 'TW', 158, 1, NOW(), NOW()),
('Tajikistan', 'TJK', 'TJ', 762, 1, NOW(), NOW()),
('Tanzania', 'TZA', 'TZ', 834, 1, NOW(), NOW()),
('Thailand', 'THA', 'TH', 764, 1, NOW(), NOW()),
('Timor-Leste', 'TLS', 'TL', 626, 1, NOW(), NOW()),
('Togo', 'TGO', 'TG', 768, 1, NOW(), NOW()),
('Tonga', 'TON', 'TO', 776, 1, NOW(), NOW()),
('Trinidad and Tobago', 'TTO', 'TT', 780, 1, NOW(), NOW()),
('Tunisia', 'TUN', 'TN', 788, 1, NOW(), NOW()),
('Turkey', 'TUR', 'TR', 792, 1, NOW(), NOW()),
('Turkmenistan', 'TKM', 'TM', 795, 1, NOW(), NOW()),
('Tuvalu', 'TUV', 'TV', 798, 1, NOW(), NOW()),
('Uganda', 'UGA', 'UG', 800, 1, NOW(), NOW()),
('Ukraine', 'UKR', 'UA', 804, 1, NOW(), NOW()),
('United Arab Emirates', 'ARE', 'AE', 784, 1, NOW(), NOW()),
('United Kingdom', 'GBR', 'GB', 826, 1, NOW(), NOW()),
('United States', 'USA', 'US', 840, 1, NOW(), NOW()),
('Uruguay', 'URY', 'UY', 858, 1, NOW(), NOW()),
('Uzbekistan', 'UZB', 'UZ', 860, 1, NOW(), NOW()),
('Vanuatu', 'VUT', 'VU', 548, 1, NOW(), NOW()),
('Vatican City', 'VAT', 'VA', 336, 1, NOW(), NOW()),
('Venezuela', 'VEN', 'VE', 862, 1, NOW(), NOW()),
('Vietnam', 'VNM', 'VN', 704, 1, NOW(), NOW()),
('Yemen', 'YEM', 'YE', 887, 1, NOW(), NOW()),
('Zambia', 'ZMB', 'ZM', 894, 1, NOW(), NOW()),
('Zimbabwe', 'ZWE', 'ZW', 716, 1, NOW(), NOW());